name: ci

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
      

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: run lint
        run: |
          yarn install --frozen-lockfile --check-files
          yarn lint:eslint
          yarn lint:prettier
          yarn typecheck
        env:
          CI: true
      - name: build
        run: yarn build:prod
